# Generated by Django 3.1 on 2020-09-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_student',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
