# Generated by Django 3.1 on 2020-09-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibraryapp', '0002_auto_20200905_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('fathername', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=250)),
                ('mobilenumber', models.CharField(max_length=150)),
            ],
        ),
    ]
